on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
      - name: "Echo changelog"
        run: echo ${{steps.build_changelog.outputs.changelog}}
      
